version: 2

sources:
  - name: football_data
    project: rob-portfolio-390000
    schema: football_data
    tables:
      - name: draft_results
      # Source: https://www.pro-football-reference.com/years/2021/draft.htm
      - name: weekly_stats_2022
      # Source: https://fantasydata.com/nfl/fantasy-football-leaders?season=2022&seasontype=1&scope=1&subscope=1&scoringsystem=1&startweek=1&endweek=1&aggregatescope=1&range=3
      - name: weekly_stats_2021

